/**
* Bridge Server API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 0.16.25
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.sagebionetworks.bridge.kmm.shared.apis

import io.ktor.client.*
import org.sagebionetworks.bridge.mpp.network.generated.models.UploadRequest
import org.sagebionetworks.bridge.mpp.network.generated.models.UploadSession

internal class UploadsApi(basePath: String = BASE_PATH, httpClient: HttpClient): AbstractApi(
    basePath
)  {

    override val httpClient = httpClient

    /**
    * Request an upload session
    * 
    * @param uploadRequest An upload request 
    * @return UploadSession
    */
    suspend fun requestUploadSession(uploadRequest: UploadRequest) : UploadSession {
        return postData<UploadRequest, UploadSession>(uploadRequest, "v3/uploads")
    }

}
