/**
* Bridge Server API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 0.25.15
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.sagebionetworks.bridge.kmm.shared.models

import org.sagebionetworks.bridge.kmm.shared.models.Phone
import kotlinx.serialization.Serializable






import kotlinx.serialization.SerialName


/**
 * Identifying fields for an account. If the account is referenced for a participant in the context of a study, it will include an `externalId` if one was assigned to the participant in that study.
 * @param firstName 
 * @param lastName 
 * @param synapseUserId 
 * @param identifier 
 * @param orgMembership 
 * @param email 
 * @param phone 
 * @param externalId 
 * @param type AccountRef
 */
@Serializable
internal data class AccountRef (
    
    @SerialName("firstName")
    val firstName: kotlin.String? = null,
    
    @SerialName("lastName")
    val lastName: kotlin.String? = null,
    
    @SerialName("synapseUserId")
    val synapseUserId: kotlin.String? = null,
    
    @SerialName("identifier")
    val identifier: kotlin.String? = null,
    
    @SerialName("orgMembership")
    val orgMembership: kotlin.String? = null,
    
    @SerialName("email")
    val email: kotlin.String? = null,
    
    @SerialName("phone")
    val phone: Phone? = null,
    
    @SerialName("externalId")
    val externalId: kotlin.String? = null,
    /* AccountRef */
    
    @SerialName("type")
    val type: kotlin.String? = null

) {

}

