/**
* Bridge Server API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 0.21.18
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.sagebionetworks.bridge.kmm.shared.models

import kotlinx.datetime.Instant
import kotlinx.serialization.Serializable

import kotlinx.serialization.SerialName

/**
 * Activity event for a participant, used for scheduling activities. 
 * @param eventId event identifier
 * @param studyId the study in which this event occurred (if null, the event is global to an entire app; these are deprecated).
 * @param answerValue answer value for a question event
 * @param timestamp ISO 8601 date and time that the event occurred
 * @param type ActivityEvent
 */
@Serializable
data class ActivityEvent (
    /* event identifier */
    @SerialName("eventId")
    val eventId: kotlin.String,
    /* ISO 8601 date and time that the event occurred */
    @SerialName("timestamp")
    val timestamp: Instant,
    /* the study in which this event occurred (if null, the event is global to an entire app; these are deprecated). */
    @SerialName("studyId")
    val studyId: kotlin.String? = null,
    /* answer value for a question event */
    @SerialName("answerValue")
    val answerValue: kotlin.String? = null,
    /* ActivityEvent */
    @SerialName("type")
    val type: kotlin.String? = null
) {

}

