/**
* Bridge Server API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 0.21.29
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.sagebionetworks.bridge.kmm.shared.models

import kotlinx.serialization.Serializable

import kotlinx.serialization.SerialName

/**
 * 
 * @param instanceGuids Session or assessment instance GUIDs. Any records that exist with these GUIDs will be returned (scoped to a specific participant in a specific study). If the assessment is a persistent assessment, all adherence records for that assessment will be returned unless includeRepeats is false. This array cannot contain more than 500 items.
 * @param assessmentIds Return adherence records for assessments with these IDs (the assessment ID is used to define a type of assessment). This array cannot contain more than 500 items.
 * @param sessionGuids Return adherence records for sessions with these GUIDs (this is the session’s GUID in a schedule and not an instance GUID, and is used to define a type of session). This array cannot contain more than 500 items.
 * @param timeWindowGuids Return adherence records for assessments in these time windows (using the time window’s GUID in a schedule to define a type of time window). This array cannot contain more than 500 items.
 * @param adherenceRecordType 
 * @param includeRepeats Where an assessment can be performed multiple times under an instance GUID, all records will be returned unless this flag is set to true. In this case, the first or last record only will be returned (depending on sort order).
 * @param currentTimestampsOnly Where a time series can be performed multiple times because a session’s trigger event is mutable, all records will be returned, unless this flag is set to true. When true, only records with recent event timestamp values will be returned. This is equivalent to sending back the user’s entire map of current event ID timestamp values via the `eventTimestamps` map in this search object. If values are also provided in the `eventTimestamps` map, each of those event IDs will override its associated event ID timestamp value, as it is provided by setting this flag to true.
 * @param eventTimestamps A mapping of event IDs to timestamp values to use when retrieving adherence records that are from sessions triggered by that ID. Only records with that exact timestamp value in their `eventTimestamp` field will be returned. In general, mobile clients will only want to retrieve records for current timestamp values when calculating schedules, so the `currentTimestampsOnly` flag provides an easy way to request that all current timestamps be used to limit search results. This map cannot contain more than 50 entries.
 * @param startTime Limit search results to records with `startedOn` values that are equal to or later than this start time (no earlier than January 1st, 2020).
 * @param endTime Limit search results to records with `startedOn` values that are equal to or earlier than this end time (no later than January 1st, 2120).
 * @param pageSize The maximum number of records in each returned page. Range can be from 1-500 records.
 * @param offsetBy The next page start offset for pagination.
 * @param sortOrder 
 * @param type AdherenceRecordsSearch
 */
@Serializable
data class AdherenceRecordsSearch (
    /* Session or assessment instance GUIDs. Any records that exist with these GUIDs will be returned (scoped to a specific participant in a specific study). If the assessment is a persistent assessment, all adherence records for that assessment will be returned unless includeRepeats is false. This array cannot contain more than 500 items. */
    @SerialName("instanceGuids")
    val instanceGuids: kotlin.collections.List<kotlin.String>? = null,
    /* Return adherence records for assessments with these IDs (the assessment ID is used to define a type of assessment). This array cannot contain more than 500 items. */
    @SerialName("assessmentIds")
    val assessmentIds: kotlin.collections.List<kotlin.String>? = null,
    /* Return adherence records for sessions with these GUIDs (this is the session’s GUID in a schedule and not an instance GUID, and is used to define a type of session). This array cannot contain more than 500 items. */
    @SerialName("sessionGuids")
    val sessionGuids: kotlin.collections.List<kotlin.String>? = null,
    /* Return adherence records for assessments in these time windows (using the time window’s GUID in a schedule to define a type of time window). This array cannot contain more than 500 items. */
    @SerialName("timeWindowGuids")
    val timeWindowGuids: kotlin.collections.List<kotlin.String>? = null,
    @SerialName("adherenceRecordType")
    val adherenceRecordType: AdherenceRecordType? = null,
    /* Where an assessment can be performed multiple times under an instance GUID, all records will be returned unless this flag is set to true. In this case, the first or last record only will be returned (depending on sort order). */
    @SerialName("includeRepeats")
    val includeRepeats: kotlin.Boolean? = null,
    /* Where a time series can be performed multiple times because a session’s trigger event is mutable, all records will be returned, unless this flag is set to true. When true, only records with recent event timestamp values will be returned. This is equivalent to sending back the user’s entire map of current event ID timestamp values via the `eventTimestamps` map in this search object. If values are also provided in the `eventTimestamps` map, each of those event IDs will override its associated event ID timestamp value, as it is provided by setting this flag to true. */
    @SerialName("currentTimestampsOnly")
    val currentTimestampsOnly: kotlin.Boolean? = null,
    /* A mapping of event IDs to timestamp values to use when retrieving adherence records that are from sessions triggered by that ID. Only records with that exact timestamp value in their `eventTimestamp` field will be returned. In general, mobile clients will only want to retrieve records for current timestamp values when calculating schedules, so the `currentTimestampsOnly` flag provides an easy way to request that all current timestamps be used to limit search results. This map cannot contain more than 50 entries. */
    @SerialName("eventTimestamps")
    val eventTimestamps: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,
    /* Limit search results to records with `startedOn` values that are equal to or later than this start time (no earlier than January 1st, 2020). */
    @SerialName("startTime")
    val startTime: kotlin.String? = null,
    /* Limit search results to records with `startedOn` values that are equal to or earlier than this end time (no later than January 1st, 2120). */
    @SerialName("endTime")
    val endTime: kotlin.String? = null,
    /* The maximum number of records in each returned page. Range can be from 1-500 records. */
    @SerialName("pageSize")
    val pageSize: kotlin.Int? = null,
    /* The next page start offset for pagination. */
    @SerialName("offsetBy")
    val offsetBy: kotlin.Int? = null,
    @SerialName("sortOrder")
    val sortOrder: SortOrder? = null,
    /* AdherenceRecordsSearch */
    @SerialName("type")
    val type: kotlin.String? = null
) {

}

