/**
* Bridge Server API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 0.21.29
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.sagebionetworks.bridge.kmm.shared.models

import kotlinx.serialization.Serializable

import kotlinx.serialization.SerialName

/**
* The AdherenceRecordType can be used to limit search results for adherence records to either assessment or session records. If not present, both records will be returned according to the criteria of the search. |Enum|Description| |---|---| |assessment|| |session|| 
* Values: "assessment","session"
*/
@Serializable
enum class AdherenceRecordType(val serialName: String? = null) {

    @SerialName("assessment")
    ASSESSMENT,

    @SerialName("session")
    SESSION;

}

