/**
* Bridge Server API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 0.21.29
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.sagebionetworks.bridge.kmm.shared.models

import kotlinx.datetime.Instant
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/**
 * A record describing the performance state of a scheduled session or assessment, as requested in a `Timeline`. Each record describes the state of a session or an assessment.
 * @param instanceGuid The session or assessment instance GUID from the timeline that led to the generation of this record. There can be more than one record under a given instance GUID if that guid is for a persistent assessment, which can be performed more than once. In this case, each record must have a unique `startedOn` timestamp (time zone differences are not enough to make it unique, it must be a unique instant in time).
 * @param startedOn The client-supplied time when the activity was started (this time comes from the client and is not validated by the server). Since adherence records only includes activities that have been started, this value is required.
 * @param finishedOn The client-supplied time when the activity was recorded as finished (this time comes from the client and is not validated by the server).
 * @param eventTimestamp The event timestamp (at the time of recording this record) that triggered the sequence of sessions and assessments which includes the scheduling item for this record. For mutable event IDs, this timestamp can change, and each time value groups a separate series of instance GUID records.
 * @param clientTimeZone An IANA Time Zone Database (TZDB) name for the participant’s time zone at the time the record is submitted. If present, this field will be validated to be a valid time zone name.
 * @param uploadedOn The timestamp when an uploaded was recorded as successfully uploaded. If this timestamp is missing, the upload has not yet reached the server.
 * @param clientData An arbitrary JSON structure that the client can use to record information about this schedule item (maximum size 65k).
 * @param type AdherenceRecord
 */
@Serializable
data class AdherenceRecord (
/* The session or assessment instance GUID from the timeline that led to the generation of this record. There can be more than one record under a given instance GUID if that guid is for a persistent assessment, which can be performed more than once. In this case, each record must have a unique `startedOn` timestamp (time zone differences are not enough to make it unique, it must be a unique instant in time). */
    @SerialName("instanceGuid")
    val instanceGuid: String,
    /* The event timestamp (at the time of recording this record) that triggered the sequence of sessions and assessments which includes the scheduling item for this record. For mutable event IDs, this timestamp can change, and each time value groups a separate series of instance GUID records. */
    @SerialName("eventTimestamp")
    val eventTimestamp: String,
    /* The client-supplied time when the activity was started (this time comes from the client and is not validated by the server). This value is normally set, but could be null if a participant declines a session or assessment. */
    @SerialName("startedOn")
    val startedOn: Instant? = null,
    /* The client-supplied time when the activity was recorded as finished (this time comes from the client and is not validated by the server). */
    @SerialName("finishedOn")
    val finishedOn: Instant? = null,
    /* An IANA Time Zone Database (TZDB) name for the participant’s time zone at the time the record is submitted. If present, this field will be validated to be a valid time zone name. */
    @SerialName("clientTimeZone")
    val clientTimeZone: String? = null,
    /* The timestamp when an uploaded was recorded as successfully uploaded. If this timestamp is missing, the upload has not yet reached the server. */
    @SerialName("uploadedOn")
    val uploadedOn: String? = null,
    /* If the participant explicitly decides to skip a session or an assessment, this can be indicated by the mobile app by setting this flag to true. This can then used when considering adherence to the protocol. */
    @SerialName("declined")
    val declined: Boolean = false,
    /* An arbitrary JSON structure that the client can use to record information about this schedule item (maximum size 65k). */
    @SerialName("clientData")
    val clientData: JsonElement? = null,
    /* AdherenceRecord */
    @SerialName("type")
    val type: String = "AdherenceRecord"
) {

}

