/**
* Bridge Server API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 0.21.29
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.sagebionetworks.bridge.kmm.shared.models

import kotlinx.serialization.Serializable

import kotlinx.serialization.SerialName

/**
 * 
 * @param records 
 * @param type AdherenceRecordUpdates
 */
@Serializable
data class AdherenceRecordUpdates (
    @SerialName("records")
    val records: List<AdherenceRecord>,
    /* AdherenceRecordUpdates */
    @SerialName("type")
    val type: String = "AdherenceRecordUpdates"
) {

}

