/**
* Bridge Server API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 0.21.29
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.sagebionetworks.bridge.kmm.shared.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

/**
 * 
 * @param requestParams 
 * @param type ResourceList
 * @param total The total number of records in the items list
 * @param items 
 */
@Serializable
data class AssessmentList (
    @SerialName("requestParams")
    val requestParams: RequestParams? = null,
    /* ResourceList */
    @SerialName("type")
    val type: String,
    /* The total number of records in the items list */
    @SerialName("total")
    val total: Int,
    @SerialName("items")
    val items: List<Assessment>
)

