/**
 * Bridge Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.16.25
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.sagebionetworks.bridge.kmm.shared.models

import kotlinx.serialization.Serializable

import kotlinx.serialization.SerialName

/**
 * Describes the content of the `User-Agent` field in the format that is accepted and understandable to the Bridge server (see [REST API getting started](/articles/rest.html)).
 * @param appName The name of the application (e.g. \"Cardio Health\").
 * @param appVersion The version of the application (must be a number, and should increase with every new release of the application).
 * @param deviceName Information about the device (e.g. \"Unknown iPhone\").
 * @param osName The name of the operating system (conventional names are \"Android\" and \"iPhone OS\").
 * @param osVersion The version of the operating system (e.g. \"10.0.3\").
 * @param sdkName The name of the SDK being used (e.g. \"BridgeJavaSDK\").
 * @param sdkVersion The version of the SDK being used (e.g. \"4\").
 * @param type ClientInfo
 */
@Serializable
data class ClientInfo (
    /* The name of the application (e.g. \"Cardio Health\"). */
    @SerialName("appName")
    val appName: String? = null,
    /* The version of the application (must be a number, and should increase with every new release of the application).  */
    @SerialName("appVersion")
    val appVersion: Int? = null,
    /* Information about the device (e.g. \"Unknown iPhone\"). */
    @SerialName("deviceName")
    val deviceName: String? = null,
    /* The name of the operating system (conventional names are \"Android\" and \"iPhone OS\").  */
    @SerialName("osName")
    val osName: String? = null,
    /* The version of the operating system (e.g. \"10.0.3\"). */
    @SerialName("osVersion")
    val osVersion: String? = null,
    /* The name of the SDK being used (e.g. \"BridgeJavaSDK\"). */
    @SerialName("sdkName")
    val sdkName: String? = null,
    /* The version of the SDK being used (e.g. \"4\"). */
    @SerialName("sdkVersion")
    val sdkVersion: Int? = null,
    /* ClientInfo */
    @SerialName("type")
    val type: String? = null
)
