/**
* Bridge Server API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 0.21.18
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.sagebionetworks.bridge.kmm.shared.models

import kotlinx.serialization.Serializable

import kotlinx.serialization.SerialName

/**
 * Colors to differentiate this assessment in a UI.
 * @param foreground A color value (in hex color triplet  or
 * @param background A color value (in hex color triplet  or
 * @param activated A color value (in hex color triplet  or
 * @param inactivated A color value (in hex color triplet  or
 * @param type ColorScheme
 */
@Serializable
data class ColorScheme (
    /* A color value (in hex color triplet  or */
    @SerialName("foreground")
    val foreground: kotlin.String? = null,
    /* A color value (in hex color triplet  or */
    @SerialName("background")
    val background: kotlin.String? = null,
    /* A color value (in hex color triplet  or */
    @SerialName("activated")
    val activated: kotlin.String? = null,
    /* A color value (in hex color triplet  or */
    @SerialName("inactivated")
    val inactivated: kotlin.String? = null,
    /* ColorScheme */
    @SerialName("type")
    val type: kotlin.String? = null
) {

}

