/**
* Bridge Server API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 0.16.25
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.sagebionetworks.bridge.kmm.shared.models

import kotlinx.serialization.Serializable

import kotlinx.serialization.SerialName

/**
 * A pointer to a configuration element.
 * @param id Schema ID
 * @param revision Revision number
 * @param type ConfigReference
 */
@Serializable
data class ConfigReference (
    /* Schema ID */
    @SerialName("id")
    val id: String,
    /* Revision number */
    @SerialName("revision")
    val revision: Long,
    /* ConfigReference */
    @SerialName("type")
    val type: String? = null
)

