/**
* Bridge Server API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 0.22.11
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.sagebionetworks.bridge.kmm.shared.models

import kotlinx.serialization.Serializable

import kotlinx.serialization.SerialName

/**
* The purpose of this contact.  |Type|Description| |---|---| |irb|Either the IRB that approved the research, or in secondary jurisdictions, an “assenting” IRB that reviewed the initial approval and accepted it for their own jurisdiction.| |principal_investigator|Principal investigator of the study. Conceivably there can be one of these for every jurisdiction, but this is rare.| |investigator|Position could be co-investigator, medical monitor, repository guardian, etc. Nevertheless, this person is not presented as a point of contact (use a support role for that).| |sponsor|The institution funding the study and/or providing IRB oversight. Sometimes the institution the Principal Investigator is affiliated with.| |study_support|Position could be study coordinator or study contact—the person the participant should contact about participation in the study.| |technical_support|Support person or department for the technology being utilized (mobile app, website, device provisioning, etc.).| 
* Values: "irb","principal_investigator","investigator","sponsor","study_support","technical_support"
*/
@Serializable
enum class ContactRole(val serialName: String? = null) {

    @SerialName("irb")
    IRB,

    @SerialName("principal_investigator")
    PRINCIPAL_INVESTIGATOR,

    @SerialName("investigator")
    INVESTIGATOR,

    @SerialName("sponsor")
    SPONSOR,

    @SerialName("study_support")
    STUDY_SUPPORT,

    @SerialName("technical_support")
    TECHNICAL_SUPPORT;

}

