/**
* Bridge Server API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 0.22.11
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.sagebionetworks.bridge.kmm.shared.models

import kotlinx.serialization.Serializable

import kotlinx.serialization.SerialName

/**
 * A contact for the study. This is for display to the participants of the study, and in other catalogs of the studies that are available.
 * @param role 
 * @param name 
 * @param position 
 * @param affiliation 
 * @param address 
 * @param email 
 * @param phone 
 * @param jurisdiction 
 * @param type Contact
 */
@Serializable
data class Contact (
    @SerialName("role")
    val role: ContactRole,
    @SerialName("name")
    val name: String,
    @SerialName("position")
    val position: String? = null,
    @SerialName("affiliation")
    val affiliation: String? = null,
    @SerialName("address")
    val address: Address? = null,
    @SerialName("email")
    val email: String? = null,
    @SerialName("phone")
    val phone: Phone? = null,
    @SerialName("jurisdiction")
    val jurisdiction: String? = null,
    /* Contact */
    @SerialName("type")
    val type: String? = null
) {

}

