/**
* Bridge Server API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 0.16.25
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.sagebionetworks.bridge.kmm.shared.models

import kotlinx.serialization.Serializable

import kotlinx.serialization.SerialName

/**
 * Some objects, like Subpopulations and the schedules in a CriteriaScheduleStrategy, are matched against user criteria in order to return the correct object. The criteria against which user information will be matched are described in the Criteria object. See [Customizing Content for Participants](/articles/filtering.html) for a fuller explanation.  
 * @param language A two-letter language code. The the must declare an `Accept-Language` header with this language in order to match this object. 
 * @param allOfGroups One or more data groups; the user must have all these data groups to match.
 * @param noneOfGroups One or more data groups; the user must have none of these data groups to match.
 * @param allOfSubstudyIds One or more substudy IDs; the user must be assigned to all these substudies to match.
 * @param noneOfSubstudyIds One or more substudy IDs; the user cannot be assigned to any of these substudies for the associated object to match.
 * @param minAppVersions A map of operating system names to minimum app versions. The user must send a `User-Agent` header in a prescribed format, that declares the app version to be equal to or greater than this version number, in order to match. 
 * @param maxAppVersions A map of operating system names to minimum app versions. The user must send a `User-Agent` header in a prescribed format, that declares the app version to be equal to or less than this version number, in order to match. 
 * @param type Criteria
 */
@Serializable
data class Criteria (
    /* A two-letter language code. The the must declare an `Accept-Language` header with this language in order to match this object.  */
    @SerialName("language")
    val language: String? = null,
    /* One or more data groups; the user must have all these data groups to match. */
    @SerialName("allOfGroups")
    val allOfGroups: List<String>? = null,
    /* One or more data groups; the user must have none of these data groups to match. */
    @SerialName("noneOfGroups")
    val noneOfGroups: List<String>? = null,
    /* One or more substudy IDs; the user must be assigned to all these substudies to match. */
    @SerialName("allOfSubstudyIds")
    val allOfSubstudyIds: List<String>? = null,
    /* One or more substudy IDs; the user cannot be assigned to any of these substudies for the associated object to match. */
    @SerialName("noneOfSubstudyIds")
    val noneOfSubstudyIds: List<String>? = null,
    /* A map of operating system names to minimum app versions. The user must send a `User-Agent` header in a prescribed format, that declares the app version to be equal to or greater than this version number, in order to match.  */
    @SerialName("minAppVersions")
    val minAppVersions: Map<String, Int>? = null,
    /* A map of operating system names to minimum app versions. The user must send a `User-Agent` header in a prescribed format, that declares the app version to be equal to or less than this version number, in order to match.  */
    @SerialName("maxAppVersions")
    val maxAppVersions: Map<String, Int>? = null,
    /* Criteria */
    @SerialName("type")
    val type: String? = null
)

