/**
* Bridge Server API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 0.23.30
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.sagebionetworks.bridge.kmm.shared.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName


/**
 * Model object representing a date range, which includes start date and end date as calendar dates (YYYY-MM-DD). 
 * @param startDate Start date of the date range (YYYY-MM-DD).
 * @param endDate Start date of the date range (YYYY-MM-DD).
 */
@Serializable
public data class DateRange (
    /* Start date of the date range (YYYY-MM-DD). */
    
    @SerialName("startDate")
    val startDate: kotlin.String? = null,
    /* Start date of the date range (YYYY-MM-DD). */
    
    @SerialName("endDate")
    val endDate: kotlin.String? = null

) {

}

