/**
* Bridge Server API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 0.25.15
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.sagebionetworks.bridge.kmm.shared.models

import org.sagebionetworks.bridge.kmm.shared.models.AccountRef
import kotlinx.serialization.Serializable






import kotlinx.serialization.SerialName


/**
 * Details about the enrollment of a user in a study
 * @param studyId 
 * @param participant 
 * @param consentRequired 
 * @param enrolledOn 
 * @param enrolledBy 
 * @param externalId 
 * @param withdrawnOn 
 * @param withdrawnBy 
 * @param withdrawalNote 
 * @param note An optional, study-scoped participant note.
 * @param type EnrollmentDetail
 */
@Serializable
internal data class EnrollmentDetail (
    
    @SerialName("studyId")
    val studyId: kotlin.String,
    
    @SerialName("participant")
    val participant: AccountRef,
    
    @SerialName("consentRequired")
    val consentRequired: kotlin.Boolean,
    
    @SerialName("enrolledOn")
    val enrolledOn: kotlin.String,
    
    @SerialName("enrolledBy")
    val enrolledBy: AccountRef? = null,
    
    @SerialName("externalId")
    val externalId: kotlin.String? = null,
    
    @SerialName("withdrawnOn")
    val withdrawnOn: kotlin.String? = null,
    
    @SerialName("withdrawnBy")
    val withdrawnBy: AccountRef? = null,
    
    @SerialName("withdrawalNote")
    val withdrawalNote: kotlin.String? = null,
    /* An optional, study-scoped participant note. */
    
    @SerialName("note")
    val note: kotlin.String? = null,
    /* EnrollmentDetail */
    
    @SerialName("type")
    val type: kotlin.String? = null

) {

}

