/**
* Bridge Server API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 0.23.30
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.sagebionetworks.bridge.kmm.shared.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName


/**
 * Details about an enrollment for the participant enrolled in the study.
 * @param externalId 
 * @param consentRequired 
 * @param enrolledOn 
 * @param withdrawnOn 
 * @param enrolledBySelf If the participant enrolled themselves, the property will be present and true. Otherwise, property will not be in JSON.
 * @param withdrawnBySelf If the participant withdrew themselves, the property will be present and true. Otherwise, property will not be in JSON.
 * @param type EnrollmentInfo
 */
@Serializable
public data class EnrollmentInfo (
    
    @SerialName("externalId")
    val externalId: kotlin.String? = null,
    
    @SerialName("consentRequired")
    val consentRequired: kotlin.Boolean? = null,
    
    @SerialName("enrolledOn")
    val enrolledOn: kotlin.String? = null,
    
    @SerialName("withdrawnOn")
    val withdrawnOn: kotlin.String? = null,
    /* If the participant enrolled themselves, the property will be present and true. Otherwise, property will not be in JSON. */
    
    @SerialName("enrolledBySelf")
    val enrolledBySelf: kotlin.Boolean? = null,
    /* If the participant withdrew themselves, the property will be present and true. Otherwise, property will not be in JSON. */
    
    @SerialName("withdrawnBySelf")
    val withdrawnBySelf: kotlin.Boolean? = null,
    /* EnrollmentInfo */
    
    @SerialName("type")
    val type: kotlin.String? = null

) {

}

