/**
* Bridge Server API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 0.23.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.sagebionetworks.bridge.kmm.shared.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Payload object for an email address or phone number. You do not provide both identifiers when using this object for a call. 
 * @param appId String identifier if the participant's app.
 * @param email Participant's email.
 * @param phone 
 * @param type Identifier
 */
@Serializable
data class Identifier (
    /* String identifier if the participant's app. */
    
    @SerialName("appId")
    val appId: kotlin.String,
    /* Participant's email. */
    
    @SerialName("email")
    val email: kotlin.String? = null,
    
    @SerialName("phone")
    val phone: Phone? = null,
    /* Identifier */
    
    @SerialName("type")
    val type: kotlin.String? = null

) {

}

