/**
* Bridge Server API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 0.25.15
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.sagebionetworks.bridge.kmm.shared.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * An indicator for an image that should be displayed. The image data is not stored in this object; this object is only used to determine which image to display.
 * @param name The name of the image to display.
 * @param type ImageResource
 * @param module The module of the image to display.
 * @param labels A collection of labels for this ImageResource. Only one label can be included for each language, and if the user’s language cannot be selected, English will be selected as a default.
 */
@Serializable
public data class ImageResource (

    /* The name of the image to display. */
    @SerialName("name")
    val name: String,

    /* ImageResource */
    @SerialName("type")
    val type: String,

    /* The module of the image to display. */
    @SerialName("module")
    val module: String? = null,

    /* A collection of labels for this ImageResource. Only one label can be included for each language, and if the user’s language cannot be selected, English will be selected as a default. */
    @SerialName("labels")
    val labels: List<Label>? = null

) {

}

