/**
* Bridge Server API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 0.22.11
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.sagebionetworks.bridge.kmm.shared.models

import kotlinx.serialization.Serializable

import kotlinx.serialization.SerialName

/**
* The outcome of IRB approval that allows this study to be executed on the Bridge platform.  |Type|Description| |---|---| |exempt|The study is considered to be exempt from human subjects research guidelines.| |approved|The study was reviewed by the IRB and its protocol is approved.| 
* Values: "exempt","approved"
*/
@Serializable
enum class IrbDecisionType(val serialName: String? = null) {

    @SerialName("exempt")
    EXEMPT,

    @SerialName("approved")
    APPROVED;

}

