/**
* Bridge Server API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 0.21.18
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.sagebionetworks.bridge.kmm.shared.models

import kotlinx.serialization.Serializable

import kotlinx.serialization.SerialName

/**
 * 
 * @param lang A valid ISO 639 alpha-2 or alpha-3 language code specifying the language of the notification.
 * @param subject Very short rendition of the notification. For example, this value will be displayed on an Apple iWatch, where the message is shown for a short time only.
 * @param message Full notification message.
 * @param type NotificationMessage
 */
@Serializable
data class NotificationMessage (
    /* Very short rendition of the notification. For example, this value will be displayed on an Apple iWatch, where the message is shown for a short time only. */
    @SerialName("subject")
    val subject: String,
    /* Full notification message. */
    @SerialName("message")
    val message: String,
    /* A valid ISO 639 alpha-2 or alpha-3 language code specifying the language of the notification. */
    @SerialName("lang")
    val lang: String? = null,
    /* NotificationMessage */
    @SerialName("type")
    val type: String? = null
) {

}

