/**
* Bridge Server API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 0.23.30
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.sagebionetworks.bridge.kmm.shared.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * The JSON data for a non-time series participant data attribute.
 * @param data A string containing the data to be saved for the participant data attribute.
 * @param identifier The identifier of the participant data.
 * @param type ParticipantData
 */
@Serializable
data class ParticipantData (
    /* A string containing the data to be saved for the participant data attribute. */
    
    @SerialName("data")
    val data: kotlinx.serialization.json.JsonObject,
    /* The identifier of the participant data. */
    
    @SerialName("identifier")
    val identifier: kotlin.String? = null,
    /* ParticipantData */
    
    @SerialName("type")
    val type: kotlin.String? = null

) {

}

