/**
* Bridge Server API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 0.21.18
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.sagebionetworks.bridge.kmm.shared.models

import kotlinx.serialization.Serializable

import kotlinx.serialization.SerialName

/**
* The assessments in a session can be presented in a fixed and sequential order, in a randomized order the participant cannot choose, or the participant may be allowed to pick and choose the assessments to do them in an order of their choosing. This enum specifies which method must be presented to the participant.  |Status|Description| |---|---| |participant_choice|The participant can perform the assessments in any order.| |sequential|The participant must perform the assessments in the order they are specified in the session.| |randomized|The assessments should be presented to the user in a randomized order.| 
* Values: "participant_choice","sequential","randomized"
*/
@Serializable
enum class PerformanceOrder(val serialName: String? = null) {

    @SerialName("participant_choice")
    PARTICIPANT_CHOICE,

    @SerialName("sequential")
    SEQUENTIAL,

    @SerialName("randomized")
    RANDOMIZED;

}

