/**
* Bridge Server API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 0.23.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.sagebionetworks.bridge.kmm.shared.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Using a token supplied in an SMS message authenticate with the server. The token remains valid, once sent, for 5 minutes.  
 * @param appId The identifier of the participant's app.
 * @param phone 
 * @param token The token that was sent to the user via SMS, that needs to be entered into the application so it can be sent back to authenticate. 
 * @param type PhoneSignIn
 */
@Serializable
data class PhoneSignin (
    /* The identifier of the participant's app. */
    
    @SerialName("appId")
    val appId: kotlin.String,
    
    @SerialName("phone")
    val phone: Phone,
    /* The token that was sent to the user via SMS, that needs to be entered into the application so it can be sent back to authenticate.  */
    
    @SerialName("token")
    val token: kotlin.String,
    /* PhoneSignIn */
    
    @SerialName("type")
    val type: kotlin.String? = null

) {

}

