/**
* Bridge Server API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 0.23.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.sagebionetworks.bridge.kmm.shared.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Make a request to sign in using an SMS message. This request will trigger a message to be sent to an existing account's phone number. The SMS message will include a numeric token that must be included in a subsequent request to the server to authenticate. 
 * @param appId The identifier for the participant's app.
 * @param phone 
 * @param type PhoneSignInRequest
 */
@Serializable
data class PhoneSignInRequest (
    /* The identifier for the participant's app. */
    
    @SerialName("appId")
    val appId: kotlin.String,
    
    @SerialName("phone")
    val phone: Phone,
    /* PhoneSignInRequest */
    
    @SerialName("type")
    val type: kotlin.String? = null

) {

}