/**
* Bridge Server API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 0.25.33
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.sagebionetworks.bridge.kmm.shared.models

import kotlinx.serialization.Serializable






import kotlinx.serialization.SerialName


/**
 * 
 * @param propName The property name of the property on the JSON object that can be edited.
 * @param label A short label for the property.
 * @param description A longer description of the property and the allowable values that it can take.
 * @param propType A type hint to a UI editor for this property. The value is not constrained to support complex types, but we suggest 'string', 'number', or 'boolean' as basic values to support with editing tools.
 * @param type PropertyInfo
 */
@Serializable
public data class PropertyInfo (
    /* The property name of the property on the JSON object that can be edited. */
    
    @SerialName("propName")
    val propName: kotlin.String,
    /* A short label for the property. */
    
    @SerialName("label")
    val label: kotlin.String,
    /* A longer description of the property and the allowable values that it can take. */
    
    @SerialName("description")
    val description: kotlin.String? = null,
    /* A type hint to a UI editor for this property. The value is not constrained to support complex types, but we suggest 'string', 'number', or 'boolean' as basic values to support with editing tools. */
    
    @SerialName("propType")
    val propType: kotlin.String? = null,
    /* PropertyInfo */
    
    @SerialName("type")
    val type: kotlin.String? = null

) {

}

