/**
* Bridge Server API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 0.21.18
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.sagebionetworks.bridge.kmm.shared.models

import kotlinx.serialization.Serializable

import kotlinx.serialization.SerialName

/**
* If the app should issue a second reminder notification, when should this reminder be issued? If null, no reminder should be shown. If present, it can be relative to when a time window starts, or relative to when the window ends. This value works with `reminderPeriod` to determine the time.   |Status|Description| |---|---| |after_window_start|Issue the reminder `reminderPeriod` after the window starts| |before_window_end|Issue the reminder `reminderPeriod` before the window ends| 
* Values: "after_window_start","before_window_end"
*/
@Serializable
enum class ReminderType(val serialName: String? = null) {

    @SerialName("after_window_start")
    AFTER_WINDOW_START,

    @SerialName("before_window_end")
    BEFORE_WINDOW_END;

}

