/**
* Bridge Server API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 0.21.29
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.sagebionetworks.bridge.kmm.shared.models

import kotlinx.serialization.Serializable

import kotlinx.serialization.SerialName

/**
* The type of report:  |Type|Description| |---|---| |participant|Reports are scoped to an individual participant and can only be seen by the participant or a researcher| |study|Reports are available to all authenticated users in a study| 
* Values: "participant","study"
*/
@Serializable
internal enum class ReportType(val serialName: String? = null) {

    @SerialName("participant")
    PARTICIPANT,

    @SerialName("study")
    STUDY;

}

