/**
* Bridge Server API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 0.25.14
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.sagebionetworks.bridge.kmm.shared.models

import kotlinx.datetime.Instant
import kotlinx.datetime.LocalDate
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName


/**
 * The JSON data for one time point of a report (either a local date in the format YYYY-MM-DD, or an ISO 8601 timestamp; report records should all use one or the other format consistently). The `date` property can be used to submit either a local date or timestamp, and the value will be returned in the `date` property as well as the `localDate` or `dateTime` property depending on the format. You can also alternative submit `localDate` or `dateTime` (but never both), and you'll get back the value in that property as well as the `date` property. Data can be for a study as a whole, or a report on a single participant, depending on the endpoint that is used to persist the data in Bridge.
 * @param data An arbitrary JSON object containing whatever data should be saved for a report.
 * @param date The date (whether local or an ISO timestamp) of the report data.
 * @param localDate The date expressed as a LocalDate (YYYY-MM-DD)
 * @param dateTime The date expressed as an ISO 8601 timestamp.
 * @param studyIds The studies this report record is associated to (these are set with the first record that is submitted and that creates a report index, and cannot be changed afterward unless the user is a study-wide user not associated to any specific study.
 * @param type ReportData
 */
@Serializable
internal data class ReportData (

    /* An arbitrary JSON object containing whatever data should be saved for a report. */
    @SerialName("data")
    val data: kotlinx.serialization.json.JsonObject,

    /* The date (whether local or an ISO timestamp) of the report data. */
    @SerialName("date")
    val date: String,

    /* The date expressed as a LocalDate (YYYY-MM-DD) */
    @SerialName("localDate")
    val localDate: LocalDate? = null,

    /* The date expressed as an ISO 8601 timestamp. */
    @SerialName("dateTime")
    val dateTime: Instant? = null,

    /* The studies this report record is associated to (these are set with the first record that is submitted and that creates a report index, and cannot be changed afterward unless the user is a study-wide user not associated to any specific study. */
    @SerialName("studyIds")
    val studyIds: List<String>? = null,

    /* ReportData */
    @SerialName("type")
    val type: String? = "ReportData"

) {

}

