/**
* Bridge Server API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 0.21.29
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.sagebionetworks.bridge.kmm.shared.models

import kotlinx.serialization.Serializable

import kotlinx.serialization.SerialName

/**
 * Type-safe object that returns request parameters submitted for a request. Only the values that are submitted in a request, or that are assigned default values by the server, will be returned with the response. Inapplicable values will be null. 
 * @param allOfGroups 
 * @param assessmentIds 
 * @param assignmentFilter 
 * @param currentTimestampsOnly 
 * @param emailFilter 
 * @param endDate 
 * @param endTime 
 * @param eventTimestamps 
 * @param idFilter 
 * @param includeDeleted 
 * @param includeRepeats 
 * @param instanceGuids 
 * @param language 
 * @param noneOfGroups 
 * @param offsetBy 
 * @param offsetKey 
 * @param pageSize 
 * @param phoneFilter 
 * @param recordType 
 * @param reportType 
 * @param scheduledOnStart 
 * @param scheduledOnEnd 
 * @param sessionGuids 
 * @param sortOrder 
 * @param startDate 
 * @param startTime 
 * @param studyId 
 * @param timeWindowGuids 
 * @param total 
 * @param summary 
 * @param tags 
 * @param categories 
 * @param minRevision 
 * @param maxRevision 
 * @param adminOnly 
 * @param orgMembership 
 * @param type RequestParams
 */
@Serializable
internal data class RequestParams (
    @SerialName("allOfGroups")
    val allOfGroups: List<String>? = null,
    @SerialName("assessmentIds")
    val assessmentIds: List<String>? = null,
    @SerialName("assignmentFilter")
    val assignmentFilter: Boolean? = null,
    @SerialName("currentTimestampsOnly")
    val currentTimestampsOnly: Boolean? = null,
    @SerialName("emailFilter")
    val emailFilter: String? = null,
    @SerialName("endDate")
    val endDate: String? = null,
    @SerialName("endTime")
    val endTime: String? = null,
    @SerialName("eventTimestamps")
    val eventTimestamps: Map<String, String>? = null,
    @SerialName("idFilter")
    val idFilter: String? = null,
    @SerialName("includeDeleted")
    val includeDeleted: Boolean? = null,
    @SerialName("includeRepeats")
    val includeRepeats: Boolean? = null,
    @SerialName("instanceGuids")
    val instanceGuids: List<String>? = null,
    @SerialName("language")
    val language: String? = null,
    @SerialName("noneOfGroups")
    val noneOfGroups: List<String>? = null,
    @SerialName("offsetBy")
    val offsetBy: Int? = null,
    @SerialName("offsetKey")
    val offsetKey: String? = null,
    @SerialName("pageSize")
    val pageSize: Int? = null,
    @SerialName("phoneFilter")
    val phoneFilter: String? = null,
    @SerialName("recordType")
    val recordType: AdherenceRecordType? = null,
    @SerialName("reportType")
    val reportType: ReportType? = null,
    @SerialName("scheduledOnStart")
    val scheduledOnStart: String? = null,
    @SerialName("scheduledOnEnd")
    val scheduledOnEnd: String? = null,
    @SerialName("sessionGuids")
    val sessionGuids: List<String>? = null,
    @SerialName("sortOrder")
    val sortOrder: SortOrder? = null,
    @SerialName("startDate")
    val startDate: String? = null,
    @SerialName("startTime")
    val startTime: String? = null,
    @SerialName("studyId")
    val studyId: String? = null,
    @SerialName("timeWindowGuids")
    val timeWindowGuids: List<String>? = null,
    @SerialName("total")
    val total: Int? = null,
    @SerialName("summary")
    val summary: Boolean? = null,
    @SerialName("tags")
    val tags: List<String>? = null,
    @SerialName("categories")
    val categories: List<ResourceCategory>? = null,
    @SerialName("minRevision")
    val minRevision: Int? = null,
    @SerialName("maxRevision")
    val maxRevision: Int? = null,
    @SerialName("adminOnly")
    val adminOnly: Boolean? = null,
    @SerialName("orgMembership")
    val orgMembership: String? = null,
    /* RequestParams */
    @SerialName("type")
    val type: String? = null
)

