/**
* Bridge Server API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 0.21.29
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.sagebionetworks.bridge.kmm.shared.models

import kotlinx.serialization.Serializable

import kotlinx.serialization.SerialName

/**
 * Type-safe object that returns request parameters submitted for a request. Only the values that are submitted in a request, or that are assigned default values by the server, will be returned with the response. Inapplicable values will be null. 
 * @param allOfGroups 
 * @param assessmentIds 
 * @param assignmentFilter 
 * @param currentTimestampsOnly 
 * @param emailFilter 
 * @param endDate 
 * @param endTime 
 * @param eventTimestamps 
 * @param idFilter 
 * @param includeDeleted 
 * @param includeRepeats 
 * @param instanceGuids 
 * @param language 
 * @param noneOfGroups 
 * @param offsetBy 
 * @param offsetKey 
 * @param pageSize 
 * @param phoneFilter 
 * @param recordType 
 * @param reportType 
 * @param scheduledOnStart 
 * @param scheduledOnEnd 
 * @param sessionGuids 
 * @param sortOrder 
 * @param startDate 
 * @param startTime 
 * @param studyId 
 * @param timeWindowGuids 
 * @param total 
 * @param summary 
 * @param tags 
 * @param categories 
 * @param minRevision 
 * @param maxRevision 
 * @param adminOnly 
 * @param orgMembership 
 * @param type RequestParams
 */
@Serializable
internal data class RequestParams (
    @SerialName("allOfGroups")
    val allOfGroups: kotlin.collections.List<kotlin.String>? = null,
    @SerialName("assessmentIds")
    val assessmentIds: kotlin.collections.List<kotlin.String>? = null,
    @SerialName("assignmentFilter")
    val assignmentFilter: kotlin.Boolean? = null,
    @SerialName("currentTimestampsOnly")
    val currentTimestampsOnly: kotlin.Boolean? = null,
    @SerialName("emailFilter")
    val emailFilter: kotlin.String? = null,
    @SerialName("endDate")
    val endDate: kotlin.String? = null,
    @SerialName("endTime")
    val endTime: kotlin.String? = null,
    @SerialName("eventTimestamps")
    val eventTimestamps: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,
    @SerialName("idFilter")
    val idFilter: kotlin.String? = null,
    @SerialName("includeDeleted")
    val includeDeleted: kotlin.Boolean? = null,
    @SerialName("includeRepeats")
    val includeRepeats: kotlin.Boolean? = null,
    @SerialName("instanceGuids")
    val instanceGuids: kotlin.collections.List<kotlin.String>? = null,
    @SerialName("language")
    val language: kotlin.String? = null,
    @SerialName("noneOfGroups")
    val noneOfGroups: kotlin.collections.List<kotlin.String>? = null,
    @SerialName("offsetBy")
    val offsetBy: kotlin.Int? = null,
    @SerialName("offsetKey")
    val offsetKey: kotlin.String? = null,
    @SerialName("pageSize")
    val pageSize: kotlin.Int? = null,
    @SerialName("phoneFilter")
    val phoneFilter: kotlin.String? = null,
    @SerialName("recordType")
    val recordType: AdherenceRecordType? = null,
    @SerialName("reportType")
    val reportType: ReportType? = null,
    @SerialName("scheduledOnStart")
    val scheduledOnStart: kotlin.String? = null,
    @SerialName("scheduledOnEnd")
    val scheduledOnEnd: kotlin.String? = null,
    @SerialName("sessionGuids")
    val sessionGuids: kotlin.collections.List<kotlin.String>? = null,
    @SerialName("sortOrder")
    val sortOrder: SortOrder? = null,
    @SerialName("startDate")
    val startDate: kotlin.String? = null,
    @SerialName("startTime")
    val startTime: kotlin.String? = null,
    @SerialName("studyId")
    val studyId: kotlin.String? = null,
    @SerialName("timeWindowGuids")
    val timeWindowGuids: kotlin.collections.List<kotlin.String>? = null,
    @SerialName("total")
    val total: kotlin.Int? = null,
    @SerialName("summary")
    val summary: kotlin.Boolean? = null,
    @SerialName("tags")
    val tags: kotlin.collections.List<kotlin.String>? = null,
    @SerialName("categories")
    val categories: kotlin.collections.List<ResourceCategory>? = null,
    @SerialName("minRevision")
    val minRevision: kotlin.Int? = null,
    @SerialName("maxRevision")
    val maxRevision: kotlin.Int? = null,
    @SerialName("adminOnly")
    val adminOnly: kotlin.Boolean? = null,
    @SerialName("orgMembership")
    val orgMembership: kotlin.String? = null,
    /* RequestParams */
    @SerialName("type")
    val type: kotlin.String? = null
) {

}

