/**
* Bridge Server API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 0.21.29
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.sagebionetworks.bridge.kmm.shared.models

import kotlinx.serialization.Serializable

import kotlinx.serialization.SerialName

/**
* A category of documentary resource link. The APIs allow you to retrieve resource links by category.  |Type|Description| |---|---| |customization_options|Documentation of the fields in an associated assessment's configuration that can be customized after importing the assessment into an app context| |data_repository|A data repository holding data that has been generated through software using this assessment| |science_documentation|Documentation of the scientific validation and norming work that has been done to assure the utility of this assessment| |developer_documentation|Documentation for software engineers of the underlying assessment configuration, and the software that exists to run the assessment in an app| |license|The license for use of the assessment or its software| |publication|A publication citation for a publication that has used data generated through this assessment.| |release_note|A release note for a specific software version of this assessment (the the minRevision and maxRevision of the `ExternalResource` should both be set to the version of the assessment being documented by this release note| |sample_app|An example of the usage of the assessment in a sample app| |sample_data|An example of the data that is generated by the assessment| |screenshot|A screenshot of the assessment in use| |see_also|A link to related research or assessments for further contextualization of the assessment| |used_in_study|A link to a Bridge app or study that has used this assessment| |website|An external website related to the assessment| |other|Any other kind of resource| 
* Values: "customization_options","data_repository","science_documentation","developer_documentation","license","publication","release_note","sample_app","sample_data","screenshot","see_also","used_in_study","website","other"
*/
@Serializable
enum class ResourceCategory(val serialName: String? = null) {

    @SerialName("customization_options")
    CUSTOMIZATION_OPTIONS,

    @SerialName("data_repository")
    DATA_REPOSITORY,

    @SerialName("science_documentation")
    SCIENCE_DOCUMENTATION,

    @SerialName("developer_documentation")
    DEVELOPER_DOCUMENTATION,

    @SerialName("license")
    LICENSE,

    @SerialName("publication")
    PUBLICATION,

    @SerialName("release_note")
    RELEASE_NOTE,

    @SerialName("sample_app")
    SAMPLE_APP,

    @SerialName("sample_data")
    SAMPLE_DATA,

    @SerialName("screenshot")
    SCREENSHOT,

    @SerialName("see_also")
    SEE_ALSO,

    @SerialName("used_in_study")
    USED_IN_STUDY,

    @SerialName("website")
    WEBSITE,

    @SerialName("other")
    OTHER;

}

