/**
* Bridge Server API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 0.16.25
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.sagebionetworks.bridge.mpp.network.generated.models

import kotlinx.serialization.Serializable

import kotlinx.serialization.SerialName

/**
 * A pointer to an upload schema defined for this survey. This schema represents a particular task or activity that the participant should perform, and tells the app which schema ID and revision number to associate the data upload with. If the revision number is set to null when creating a schedule plan, then the reference is to the most recent revision for the given OS and app version. The specific revision number that should be used will be resolved when a [ScheduledActivity](#ScheduledActivity) is created for the participant). 
 * @param id Schema ID
 * @param revision Schema revision number. Can be blank in a Schedule Plan if you want the Scheduler to automatically resolve to the latest revision for the user's app version. 
 * @param type SchemaReference
 */
@Serializable
data class SchemaReference (
    /* Schema ID */
    @SerialName("id")
    val id: String,
    /* Schema revision number. Can be blank in a Schedule Plan if you want the Scheduler to automatically resolve to the latest revision for the user's app version.  */
    @SerialName("revision")
    val revision: Long? = null,
    /* SchemaReference */
    @SerialName("type")
    val type: String? = null
) {

}

