/**
* Bridge Server API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 0.22.11
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.sagebionetworks.bridge.kmm.shared.models

import kotlinx.serialization.Serializable

import kotlinx.serialization.SerialName

/**
* |Enum|Description| |---|---| |email_password| Study expects participants to sign in with an email address and a password. | |phone_password| Study expects participants to sign in with a phone number and a password. | |external_id_password| Study expects participants to sign in with an external ID and a password. | |email_message| Study expects participants to sign in by sending an email message to the participant’s email account with a sign in code or sign in link.  | |phone_message| Study expects participants to sign in by sending an SMS message to the participant’s phone number with a sign in code or sign in link. | 
* Values: "email_password","phone_password","external_id_password","email_message","phone_message"
*/
@Serializable
enum class SignInType(val serialName: String? = null) {

    @SerialName("email_password")
    EMAIL_PASSWORD,

    @SerialName("phone_password")
    PHONE_PASSWORD,

    @SerialName("external_id_password")
    EXTERNAL_ID_PASSWORD,

    @SerialName("email_message")
    EMAIL_MESSAGE,

    @SerialName("phone_message")
    PHONE_MESSAGE;

}

