/**
* Bridge Server API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 0.21.29
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.sagebionetworks.bridge.kmm.shared.models

import kotlinx.serialization.Serializable

import kotlinx.serialization.SerialName

/**
* |Enum|Description| |---|---| |asc| Sort so that the earliest startedOn time is the first record in the returned list. | |desc| Sort so that the most recent startedOn time is the first record in the returned list. | 
* Values: "asc","desc"
*/
@Serializable
enum class SortOrder(val serialName: String? = null) {

    @SerialName("asc")
    ASC,

    @SerialName("desc")
    DESC;

}

