/**
* Bridge Server API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 0.22.11
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.sagebionetworks.bridge.kmm.shared.models

import kotlinx.serialization.Serializable

import kotlinx.serialization.SerialName

/**
* A lifecycle phase for the study.  |Type|Description| |---|---| |legacy|If not set, the study is in the LEGACY phase, and no domain logic will be applied to the study, enrollments, etc.| |design|Study is being designed and tested and has not begun. All accounts created in this phase are marked as test accounts, and schedules are still mutable. The study is not visible in public registries.| |recruitment|Study has launched and is visible in public registries, and accepting new participants through some form of enrollment. The schedule is published when the study is transitioned to this phase, and can no longer change.| |in_flight|The study is no longer accepting new participants, but participants are still active in the study. The study is no longer visible in public registries and will no longer accept new sign ups.| |analysis|All participants have completed the study protocol, and the data is being analyzed. For IRBs, this study is still open and it should still be available in administrative UIs for reporting, but no mobile or desktop participant-facing client should be engaged with the study.| |completed|Analysis has been completed and the study has been reported to the IRB. The study can now be logically deleted.| |withdrawn|The study was withdrawn before completion. It can be withdrawn from any other phase, and at that point it can be logically deleted.| 
* Values: "legacy","design","recruitment","in_flight","analysis","completed","withdrawn"
*/
@Serializable
enum class StudyPhase(val serialName: String? = null) {

    @SerialName("legacy")
    LEGACY,

    @SerialName("design")
    DESIGN,

    @SerialName("recruitment")
    RECRUITMENT,

    @SerialName("in_flight")
    IN_FLIGHT,

    @SerialName("analysis")
    ANALYSIS,

    @SerialName("completed")
    COMPLETED,

    @SerialName("withdrawn")
    WITHDRAWN;

}

