/**
* Bridge Server API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 0.22.11
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.sagebionetworks.bridge.kmm.shared.models

import kotlinx.serialization.Serializable

import kotlinx.serialization.SerialName

/**
 * An abridged study object with information that is useful for displaying, selecting, and signing into the study. 
 * @param identifier The identifier for this study.
 * @param name The name of the study.
 * @param details An in-depth description of this study for prospective participants, or to show participants after they have joined a study (the “about” screen for the study).
 * @param phase 
 * @param studyLogoUrl An URL to a logo for the study.
 * @param colorScheme 
 * @param signInTypes 
 * @param type StudyInfo
 */
@Serializable
data class StudyInfo (
    /* The identifier for this study. */
    @SerialName("identifier")
    val identifier: String? = null,
    /* The name of the study. */
    @SerialName("name")
    val name: String? = null,
    /* An in-depth description of this study for prospective participants, or to show participants after they have joined a study (the “about” screen for the study). */
    @SerialName("details")
    val details: String? = null,
    @SerialName("phase")
    val phase: StudyPhase? = null,
    /* An URL to a logo for the study. */
    @SerialName("studyLogoUrl")
    val studyLogoUrl: String? = null,
    @SerialName("colorScheme")
    val colorScheme: ColorScheme? = null,
    @SerialName("signInTypes")
    val signInTypes: List<SignInType>? = null,
    /* StudyInfo */
    @SerialName("type")
    val type: String? = null
) {

}

