/**
* Bridge Server API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 0.21.29
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.sagebionetworks.bridge.kmm.shared.models

import kotlinx.serialization.Serializable

import kotlinx.serialization.SerialName

/**
 * 
 * @param items 
 */
@Serializable
data class StudyActivityEventList (
    @SerialName("items")
    val items: kotlin.collections.List<StudyActivityEvent>? = null,
    //@SerialName("requestParams")
    //val requestParams: RequestParams? = null,
    /* ResourceList */
    @SerialName("type")
    val type: kotlin.String? = null
) {

}

