/**
* Bridge Server API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 0.23.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.sagebionetworks.bridge.kmm.shared.models


import kotlinx.datetime.DateTimePeriod
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * Information about a study burst from which some of the timeline is being derived. 
 * @param identifier Identifier for the study burst
 * @param delay ISO 8601 duration between the origin event timestamp and the first burst in the study burst sequence (days or weeks)
 * @param interval ISO 8601 duration between the burst event timestamps in days or weeks
 * @param occurrences The number of timestamps that should be generated with the `originEventId` occurs.
 * @param type StudyBurstInfo
 */
@Serializable
data class StudyBurstInfo (
    /* Identifier for the study burst */
    @SerialName("identifier")
    val identifier: String,

    /* ISO 8601 duration between the origin event timestamp and the first burst in the study burst sequence (days or weeks) */
    @SerialName("delay")
    val delay: DateTimePeriod,

    /* ISO 8601 duration between the burst event timestamps in days or weeks */
    @SerialName("interval")
    val interval: DateTimePeriod,

    /* The number of timestamps that should be generated with the `originEventId` occurs. */
    @SerialName("occurrences")
    val occurrences: Int,

    /* StudyBurstInfo */
    @SerialName("type")
    val type: kotlin.String? = null

) {

}

