/**
* Bridge Server API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 0.16.25
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.sagebionetworks.bridge.kmm.shared.models

import kotlinx.serialization.Serializable

import kotlinx.serialization.SerialName

/**
* The status of the job that exports the data of this upload to Synapse.   |Value|Description| |---|---| |not_exported|Record related to this upload has not been exported to Synapse.| |succeeded|Record related to this upload has been exported to Synapse and is available to researchers.| 
* Values: "not_exported","succeeded"
*/
@Serializable
internal enum class SynapseExporterStatus(val serialName: String? = null) {

    @SerialName("not_exported")
    NOT_EXPORTED,

    @SerialName("succeeded")
    SUCCEEDED;

}

