/**
 * Bridge Server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.23.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package org.sagebionetworks.bridge.kmm.shared.models


import kotlinx.datetime.DateTimePeriod
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * A detailed description of when a participant should perform specific sessions and assessments as part of a study, along with the metadata to show UI to the participant before loading and executing code for the assessments.
 * @param duration The length of time of the study’s protocol, after which the participant has completed the study. Events in the timeline will not extend past this duration in time.
 * @param schedule
 * @param assessments
 * @param sessions
 * @param studyBursts
 * @param totalMinutes The total number of minutes to perform all the sessions in the timeline. This information is provided for informational purposes to schedule designers.
 * @param totalNotifications The total number of notifications that could be shown to the participant (if all possible notifications are shown; fewer notifications may be shown since the participant may complete sessions before all reminders are shown for the session). This information is provided for informational purposes to schedule designers.
 * @param type Timeline
 */
@Serializable
data class Timeline (
    /* The length of time of the study’s protocol, after which the participant has completed the study. Events in the timeline will not extend past this duration in time. */

    @SerialName("duration")
    val duration: DateTimePeriod,

    @SerialName("schedule")
    val schedule: List<ScheduledSession>? = null,

    @SerialName("assessments")
    val assessments: List<AssessmentInfo>? = null,

    @SerialName("sessions")
    val sessions: List<SessionInfo>? = null,

    @SerialName("studyBursts")
    val studyBursts: List<StudyBurstInfo>? = null,
    /* The total number of minutes to perform all the sessions in the timeline. This information is provided for informational purposes to schedule designers. */

    @SerialName("totalMinutes")
    val totalMinutes: Int? = null,
    /* The total number of notifications that could be shown to the participant (if all possible notifications are shown; fewer notifications may be shown since the participant may complete sessions before all reminders are shown for the session). This information is provided for informational purposes to schedule designers. */

    @SerialName("totalNotifications")
    val totalNotifications: Int? = null,
    /* Timeline */

    @SerialName("type")
    val type: String? = null
)