/**
* Bridge Server API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 0.21.18
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.sagebionetworks.bridge.kmm.shared.models

import kotlinx.datetime.DateTimePeriod
import kotlinx.serialization.Serializable

import kotlinx.serialization.SerialName

/**
 * A detailed description of when a participant should perform specific sessions and assessments as part of a study, along with the metadata to show UI to the participant before loading and executing code for the assessments. 
 * @param duration The length of time of the study’s protocol, after which the participant has completed the study. Events in the timeline will not extend past this duration in time.
 * @param schedule 
 * @param assessments 
 * @param sessions 
 * @param type Timeline
 */
@Serializable
data class Timeline (
    /* The length of time of the study’s protocol, after which the participant has completed the study. Events in the timeline will not extend past this duration in time. */
    @SerialName("duration")
    val duration: DateTimePeriod,
    @SerialName("schedule")
    val schedule: List<ScheduledSession>? = null,
    @SerialName("assessments")
    val assessments: List<AssessmentInfo>? = null,
    @SerialName("sessions")
    val sessions: List<SessionInfo>? = null,
    /* Timeline */
    @SerialName("type")
    val type: String? = null
) {

}

