/**
* Bridge Server API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 0.16.25
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.sagebionetworks.bridge.kmm.shared.models

import kotlinx.serialization.Serializable

import kotlinx.serialization.SerialName

/**
 * 
 * @param id The identifier for this upload.
 * @param messageList An array of error messages if failures occurred during validation.
 * @param status 
 * @param record 
 * @param type UploadValidationStatus
 */
@Serializable
internal data class UploadValidationStatus (
    /* The identifier for this upload. */
    @SerialName("id")
    val id: String? = null,
    /* An array of error messages if failures occurred during validation. */
    @SerialName("messageList")
    val messageList: List<String>? = null,
    @SerialName("status")
    val status: UploadStatus? = null,
    @SerialName("record")
    val record: HealthDataRecord? = null,
    /* UploadValidationStatus */
    @SerialName("type")
    val type: String? = null
)

