/**
* Bridge Server API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 0.16.25
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.sagebionetworks.bridge.kmm.shared.models

import kotlinx.serialization.Serializable

import kotlinx.serialization.SerialName

/**
* The status of the upload:  |Status|Description| |---|---| |unknown|Upload status is unknown. This is generally used for older data formats (namely, Upload v1), which had a binary complete flag rather than an UploadStatus.| |requested|Initial state. Upload is requested. User needs to upload to specified URL and call uploadComplete.| |validation_in_progress|Client process has called uploadComplete. Upload validation is currently taking place.| |validation_failed|Upload validation has failed (see the validationMessageList for further details).| |succeeded|Upload has succeeded, including validation. Note that export to Synapse is a separate step.| 
* Values: "unknown","requested","validation_in_progress","validation_failed","duplicate","succeeded"
*/
@Serializable
internal enum class UploadStatus(val serialName: String? = null) {

    @SerialName("unknown")
    UNKNOWN,

    @SerialName("requested")
    REQUESTED,

    @SerialName("validation_in_progress")
    VALIDATION_IN_PROGRESS,

    @SerialName("validation_failed")
    VALIDATION_FAILED,

    @SerialName("duplicate")
    DUPLICATE,

    @SerialName("succeeded")
    SUCCEEDED;

}

