/**
* Bridge Server API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 0.16.25
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.sagebionetworks.bridge.mpp.network.generated.models

import kotlinx.serialization.Serializable

import kotlinx.serialization.SerialName

/**
 * 
 * @param id The upload ID. The client needs to use this ID to call Bridge when the upload is complete. 
 * @param url A pre-signed URL for doing a PUT upload of the data. The URL will remain valid for 24 hours once created on the Bridge side. 
 * @param expires The ISO 8601 date and time stamp at which this session will expire. 
 * @param type UploadSession
 */
@Serializable
internal data class UploadSession (
    /* The upload ID. The client needs to use this ID to call Bridge when the upload is complete.  */
    @SerialName("id")
    val id: String? = null,
    /* A pre-signed URL for doing a PUT upload of the data. The URL will remain valid for 24 hours once created on the Bridge side.  */
    @SerialName("url")
    val url: String,
    /* The ISO 8601 date and time stamp at which this session will expire.  */
    @SerialName("expires")
    val expires: String? = null,
    /* UploadSession */
    @SerialName("type")
    val type: String? = null
)

