/**
* Bridge Server API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 0.23.30
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.sagebionetworks.bridge.kmm.shared.models

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName


/**
 * A record of a complete consent (including both the dates of consent and withdrawal, if applicable);
 * @param subpopulationGuid The consent group that the participant agreed to participate in.
 * @param consentCreatedOn ISO 8601 date and time that the consent was created on.
 * @param name Full name as entered by the participant.
 * @param birthdate ISO 8601 date string (e.g. \"YYYY-MM-DD\").
 * @param imageData The signature image in a base 64 encoding.
 * @param imageMimeType The IANA mime type indicator for the image (e.g. \"image/png\").
 * @param signedOn ISO 8601 date and time that the consent was signed by the user.
 * @param withdrewOn ISO 8601 date and time that the user withdrew the consent, if the user withdrew from a study (note that later consent records may re-enroll the user in the study; nothing prevents users from joining and quitting a study multiple times). 
 * @param hasSignedActiveConsent True if the user signed the most recently published version of the consent, false otherwise. 
 * @param type UserConsentHistory
 */
@Serializable
public data class UserConsentHistory (
    /* The consent group that the participant agreed to participate in. */
    
    @SerialName("subpopulationGuid")
    val subpopulationGuid: kotlin.String? = null,
    /* ISO 8601 date and time that the consent was created on. */
    
    @SerialName("consentCreatedOn")
    val consentCreatedOn: kotlin.String? = null,
    /* Full name as entered by the participant. */
    
    @SerialName("name")
    val name: kotlin.String? = null,
    /* ISO 8601 date string (e.g. \"YYYY-MM-DD\"). */
    
    @SerialName("birthdate")
    val birthdate: kotlin.String? = null,
    /* The signature image in a base 64 encoding. */
    
    @SerialName("imageData")
    val imageData: kotlin.String? = null,
    /* The IANA mime type indicator for the image (e.g. \"image/png\"). */
    
    @SerialName("imageMimeType")
    val imageMimeType: kotlin.String? = null,
    /* ISO 8601 date and time that the consent was signed by the user. */
    
    @SerialName("signedOn")
    val signedOn: kotlin.String? = null,
    /* ISO 8601 date and time that the user withdrew the consent, if the user withdrew from a study (note that later consent records may re-enroll the user in the study; nothing prevents users from joining and quitting a study multiple times).  */
    
    @SerialName("withdrewOn")
    val withdrewOn: kotlin.String? = null,
    /* True if the user signed the most recently published version of the consent, false otherwise.  */
    
    @SerialName("hasSignedActiveConsent")
    val hasSignedActiveConsent: kotlin.Boolean? = null,
    /* UserConsentHistory */
    
    @SerialName("type")
    val type: kotlin.String? = null

) {

}

