/**
* Bridge Server API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 0.16.25
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.sagebionetworks.bridge.kmm.shared.models

import kotlinx.serialization.Serializable

import kotlinx.serialization.SerialName

/**
* This value should always be set to production.
* Values: "local","develop","staging","production"
*/
@Serializable
enum class Environment(val serialName: String? = null) {

    @SerialName("local")
    LOCAL,

    @SerialName("develop")
    DEVELOP,

    @SerialName("staging")
    STAGING,

    @SerialName("production")
    PRODUCTION;

}

