/**
* Bridge Server API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 0.16.25
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.sagebionetworks.bridge.kmm.shared.models

import kotlinx.serialization.Serializable

import kotlinx.serialization.SerialName

/**
* |Enum|Description| |---|---| |no_sharing| Do not share data generated by this participant with the study team;| |sponsors_and_partners|Share data with the study researchers and their researcher partners only;| |all_qualified_researchers|Share data with researchers who qualify under the specific governance qualifications to access the study's data set. This may include researchers beyond the sponsors of the original study.| 
* Values: "no_sharing","sponsors_and_partners","all_qualified_researchers"
*/
@Serializable
enum class SharingScope(val serialName: String? = null) {

    @SerialName("no_sharing")
    NO_SHARING,

    @SerialName("sponsors_and_partners")
    SPONSORS_AND_PARTNERS,

    @SerialName("all_qualified_researchers")
    ALL_QUALIFIED_RESEARCHERS;

}

